title: <p align="center"> Baban Bandgar </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://in.linkedin.com/in/baban-bandgar-3384b731/">LinkedIn</a> |
  <a href="https://github.com/babanb">GitHub</a>
  
  <br>   
  I'm working on Full Stack development, ChatBots, Machine learning & NLP related problems.
  <br>
  </p>
theme: jekyll-theme-minimal
